version: '3.8'

services:
  # Backend API
  map-backend:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    container_name: rkk-map-backend
    env_file: .env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/your_database.db
    volumes:
      - data:/app/data
    restart: unless-stopped
    networks:
      - rkk-network

  # Telegram Bot
  bot:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    container_name: rkk-bot
    command: ["python", "-m", "app_bot.bot"]
    env_file: .env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/your_database.db
    volumes:
      - data:/app/data
    restart: unless-stopped
    depends_on:
      - map-backend
    networks:
      - rkk-network

  # Мы переименовали map-frontend в nginx для ясности, так как он выполняет роль Nginx
  nginx:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile # Этот Dockerfile должен устанавливать Nginx и копировать статику Vue
      args:
        VITE_YANDEX_MAPS_API_KEY: ${VITE_YANDEX_MAPS_API_KEY}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: rkk-nginx # Изменили имя контейнера для ясности
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - map-backend
    networks:
      - rkk-network
    # УБРАЛИ СЛОЖНУЮ КОМАНДУ. Nginx просто запускается.

  # Certbot для автоматического обновления сертификатов
  certbot:
    image: certbot/certbot
    container_name: rkk-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # ИЗМЕНЕННАЯ КОМАНДА: проверяет обновление и перезагружает Nginx при успехе
    command: renew --quiet --post-hook "nginx -s reload"
    restart: unless-stopped
    depends_on:
      - nginx # Явно указываем зависимость

networks:
  rkk-network:
    driver: bridge

volumes:
  data: