# Версия синтаксиса docker-compose
version: '3.8'

# --- Секция определения сервисов (наших контейнеров) ---
services:

  # 1. Сервис Фронтенда (Nginx + Vue)
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        - VITE_YANDEX_MAPS_API_KEY=${VITE_YANDEX_MAPS_API_KEY}
    container_name: rkk_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  # 2. Сервис Бэкенда (FastAPI)
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: rkk_backend
    env_file:
      - .env
    volumes:
      - db_data:/app/database
    restart: always

  # 3. Сервис Телеграм-бота (Aiogram)
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    container_name: rkk_bot
    command: sh -c "sleep 5 && python -m app_bot.bot"
    env_file:
      - .env
    volumes:
      - db_data:/app/database
    depends_on:
      - backend
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/app/database
    depends_on:
      - backend
    restart: always

# --- Секция определения томов (хранилищ данных) ---
volumes:
  # Создаем именованный том для хранения нашей базы данных.
  db_data: