# Используем официальный Python 3.13
FROM python:3.13-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем все requirements
COPY app_bot/requirements.txt ./app_bot/
COPY map_backend/requirements.txt ./map_backend/

# Устанавливаем зависимости для обоих модулей
RUN pip install --no-cache-dir -r ./app_bot/requirements.txt && \
    pip install --no-cache-dir -r ./map_backend/requirements.txt

# Копируем весь проект (бот может импортировать из map_backend)
COPY app_bot ./app_bot
COPY map_backend ./map_backend

# Команда запуска бота
CMD ["python", "-m", "app_bot.bot"]