version: '3.8'

services:
  # ... сервисы map-backend и bot остаются без изменений ...
  map-backend:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    container_name: rkk-map-backend
    env_file: .env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/your_database.db
    volumes:
      - data:/app/data
    restart: unless-stopped
    networks:
      - rkk-network

  bot:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    container_name: rkk-bot
    command: ["python", "-m", "app_bot.bot"]
    env_file: .env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/your_database.db
    volumes:
      - data:/app/data
    restart: unless-stopped
    depends_on:
      - map-backend
    networks:
      - rkk-network

  nginx:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
      args:
        VITE_YANDEX_MAPS_API_KEY: ${VITE_YANDEX_MAPS_API_KEY}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: rkk-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - map-backend
    networks:
      - rkk-network
    command: sh -c "nginx -g 'daemon off;' & while true; do sleep 1d; nginx -s reload; done"

  certbot:
    image: certbot/certbot
    container_name: rkk-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # ---- НАСТОЯЩЕЕ ИСПРАВЛЕНИЕ ----
    # 1. Переопределяем точку входа, чтобы запускать оболочку sh
    entrypoint: /bin/sh
    # 2. Передаем наш скрипт как команду для этой оболочки
    command: -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    # -------------------------------
    restart: unless-stopped
    depends_on:
      - nginx

networks:
  rkk-network:
    driver: bridge

volumes:
  data: